### ISSUE TITLE
`isqrt` shadows Julia's built-in function

### ISSUE THREAD

**Issue by simonp0420** [stla/EllipticFunctions.jl#12]
I noticed this while preparing PR#10.   It would be best to rename this function to something else, say, `csqrt` for example.  The current name could easily cause confusion for those reading the code base, thinking that `isqrt` refers to [this](https://docs.julialang.org/en/v1/base/math/#Base.isqrt) function.

**Comment by stla** [comment]
Thanks. I've just done the renaming.
