### ISSUE TITLE
Replace `@assert`s

### ISSUE THREAD

**Issue by simonp0420** [stla/EllipticFunctions.jl#27]
There are currently 30 occurrences in the code of the following type of argument authentication:
```julia
@assert condition ArgumentError("some string")
```
which I believe is intended to throw an `ArgumentError` when `condition` is false.  However, there are two problems here.  First, the current code will always throw an `AssertionError`:
```julia
julia> q = 1
1

julia> @assert abs(q) < 1 ArgumentError("Invalid `q`.")
ERROR: AssertionError: ArgumentError("Invalid `q`.")
Stacktrace:
 [1] top-level scope
   @ REPL[7]:1 
```
Compare this to the following:
```julia
julia> abs(q) < 1 || throw(ArgumentError("Invalid q"))
ERROR: ArgumentError: Invalid q
Stacktrace:
 [1] top-level scope
   @ REPL[8]:1
```
Only the latter case actually throws an `ArgumentError`.

Second, as documented in the Warning box [in this section of the Julia manual](https://docs.julialang.org/en/v1/base/base/#Base.@assert):
> An assert might be disabled at various optimization levels. Assert should therefore only be used as a debugging tool and not used for authentication verification...

So I propose to replace these assertions with standard tests that throw the appropriate, desired error type.  Also, in accordance with the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself#:~:text=%22Don't%20repeat%20yourself%22,redundancy%20in%20the%20first%20place) principle I propose replacing identical checks on e.g. `q` in various places with a call to, say, a `validateq` function that performs the desired check and throw.

@stla if you concur, I will be happy to set up the PR for these proposed changes.

**Comment by stla** [comment]
Ok 👍 

Thank you for all these informations.
